### PR TITLE
unify l1-evm codes and l2-evm codes; add ci for both

### PR DESCRIPTION
**Pull request by lispc**
### Description

[_PR description_]

### Issue Link

[_link issue here_]

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Contents

- [_item_]

### Rationale

[_design decisions and extended information_]

### How Has This Been Tested?

[_explanation_]

<hr>

## How to fill a PR description 

Please give a concise description of your PR.

The target readers could be future developers, reviewers, and auditors. By reading your description, they should easily understand the changes proposed in this pull request.

MUST: Reference the issue to resolve

### Single responsability

Is RECOMMENDED to create single responsibility commits, but not mandatory.

Anyway, you MUST enumerate the changes in a unitary way, e.g.

```
This PR contains:
- Cleanup of xxxx, yyyy
- Changed xxxx to yyyy in order to bla bla
- Added xxxx function to ...
- Refactored ....
```

### Design choices

RECOMMENDED to:
- What types of design choices did you face?
- What decisions you have made?
- Any valuable information that could help reviewers to think critically

### CODE REVIEW

**Comment by lispc** [comment]
failed

```
bytecode_circuit::circuit::tests::bytecode_full
    bytecode_circuit::circuit::tests::bytecode_invalid_byte_data
    bytecode_circuit::circuit::tests::bytecode_invalid_hash_data
    bytecode_circuit::circuit::tests::bytecode_invalid_is_code
    bytecode_circuit::circuit::tests::bytecode_push
    bytecode_circuit::circuit::tests::bytecode_simple
    bytecode_circuit::circuit::tests::bytecode_unrolling
    evm_circuit::execution::begin_tx::test::begin_tx_precompile
    evm_circuit::execution::begin_tx::test::begin_tx_precompile_with_value
    evm_circuit::execution::blockhash::test::blockhash_gadget_large
    evm_circuit::execution::blockhash::test::blockhash_gadget_simple
    super_circuit::super_circuit_tests::serial_test_super_circuit_1tx_1max_tx
    super_circuit::super_circuit_tests::serial_test_super_circuit_1tx_2max_tx
    super_circuit::super_circuit_tests::serial_test_super_circuit_1tx_deploy_2max_tx
    super_circuit::super_circuit_tests::serial_test_super_circuit_2tx_2max_tx
    super_circuit::super_circuit_tests::serial_test_super_circuit_2tx_4max_tx
```

**Comment by lispc** [comment]
TODO: use "poseidon-codehash" feature to filter contraints like "keccak256_table_lookup(cur.value_rlc, cur.length, cur.hash)"

**Comment by noel2004** [comment]
> failed cases:
> 
> 1. bytecode_invalid_hash_data.  fix or ignore? @noel2004
> 2. create related. how to fix them? @roynalnaruto

Currently the codehash lookup is disabled when `poseidon-codehash` is actived (for the rlc encoding issue). This test is supposed to be fine after the issue is resolved. So we can just leave it there or ignore it temporarily

**Comment by roynalnaruto** [comment]
I am working on making `CREATE/CREATE2` opcode gadget compatible with the dual code hash changes here: https://github.com/scroll-tech/zkevm-circuits/pull/443

**Comment by lispc** [comment]
@noel2004 can have a look at the comment above by rohit.  I think the 2nd problem will soon be fixed with new changes related to poseidon lookups?

**Comment by noel2004** [comment]
> @noel2004 can have a look at the comment above by rohit. I think the 2nd problem will soon be fixed with new changes related to poseidon lookups?

ok. I will look at it. From Rohit's comment it need some change in copycircuit and I would try to understand how it works then fix it

**Comment by lispc** [comment]
oh no.. let me debug..

**Comment by lispc** [comment]
Wake up self hosted server takes hangs.. @silathdiir

**Comment by silathdiir** [comment]
> Wake up self hosted server hangs.. @silathdiir

Fixed to wake up self-host servers concurrently, and add some debug logs in commit https://github.com/scroll-tech/zkevm-circuits/pull/438/commits/6fa1be505a89f0d8ff71bc0412fe1487c5d77fc5.

**Pull request merged**
