### PR TITLE
`RecursionCircuit` and updated `BatchCircuit`

### PR DESCRIPTION
**Pull request by noel2004**
This PR induce a new aggregation layer to aggregate multiple snarks from batch circuit, using an recursive scheme:

[doc](https://www.notion.so/scrollzkp/Aggregate-multiple-batches-32e3fdff9bda4e48b181855574e9f812?pvs=4)

### CODE REVIEW

**Comment by lispc** [comment]
1. is the bundle config file here is used for production?  if not, there should be some code to let recursion circuit use "layer5" config, where is that code?

2. withdraw root is "Additional public input that are unchanged over all the SNARKs".  not too clear to me.  You mean these are public inputs not to be "chained"?

**Comment by noel2004** [comment]
> 1. is the bundle config file here is used for production?  if not, there should be some code to let recursion circuit use "layer5" config, where is that code?
> 2. withdraw root is "Additional public input that are unchanged over all the SNARKs".  not too clear to me.  You mean these are public inputs not to be "chained"?

1. If indicate the `bundle_circuit.config` file under `aggregator/config`: No. This file is only used by the unit test of recursion circuit, so we need 5 adv colums for this config since one unit test would recursive prove a recursion circuit itself. And maybe we should not naming it as "bundle" i think.

Recursiion circuit (bundle) use a "layer5" config here: https://github.com/scroll-tech/zkevm-circuits/blob/8846bd40a42fd995276ed9508d16c78fb938ac9f/prover/src/aggregator/prover.rs#L229-L236

2. I think it is not "unchanged" but "do not involved in state transition". I consider these PIs are "not require to be verified by state transition", because they are in fact involved with (or say, decided by) state root. The doc has some irriadiation about them: 
https://www.notion.so/scrollzkp/Upgrade-4-Darwin-Documentation-05a3ecb59e9d4f288254701f8c888173?pvs=4#62a0b2058b9842188b5bd5e7267220ca

**Comment by lispc** [comment]
ok i find this line `env::set_var("BUNDLE_CONFIG", layer_config_path(id));`

**Review by lispc — APPROVED** [review]

**Review by roynalnaruto — APPROVED** [review]
Great work @noel2004 🎉

**Pull request merged**
