### PR TITLE
CALLDATALOAD opcode

### PR DESCRIPTION
**Pull request by roynalnaruto**
Branched off [op-calldatacopy](https://github.com/appliedzkp/zkevm-circuits/pull/297)

Pending:
- [x] Tests
- [x]  [Specs PR](https://github.com/scroll-tech/zkevm-specs/pull/34)

### CODE REVIEW

**Review by icemelon — COMMENTED** [review]
overall looks good. will check again after calldatacopy is merged

**Comment by roynalnaruto** [comment]
@icemelon should we open a PR to upstream?

**Comment by icemelon** [comment]
@roynalnaruto Yes, you should open a PR

**Comment by roynalnaruto** [comment]
Moving PR to upstream

**Pull request closed without merging**
