### PR TITLE
test/keccak: unittests for word split

### PR DESCRIPTION
**Pull request by naure**
### Description

By @huwenqing0606.

Add unittests around Keccak word split.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by naure** [comment]
This is similar to this PR, some parts may be redundant (to check). https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1274

**Comment by huwenqing0606** [comment]
Yes. We may consider merging the two. Also I feel `split` and `split_uniform` maybe combined into one module to make things look simpler...

**Comment by huwenqing0606** [comment]
> This is similar to this PR, some parts may be redundant (to check). [privacy-scaling-explorations#1274](https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1274)

I looked at #1274, and I think just using your PR would be fine for this test. :)

**Comment by huwenqing0606** [comment]
due to previous comment this PR can be closed

**Pull request closed without merging**
