### PR TITLE
the scroll stable branch

### PR DESCRIPTION
**Pull request by lispc**

### CODE REVIEW

**Comment by kunxian-xia** [comment]
RLP circuit PR: #233

**Comment by kunxian-xia** [comment]
Tx circuit PR: #220, 
PI circuit PR: #220

**Comment by lispc** [comment]
the CI is becoming slower and slower... We may need to re-pick this: https://github.com/scroll-tech/zkevm-circuits/pull/193

**Comment by kunxian-xia** [comment]
Yeah, I think so. Running `make test` on my local machine(with 72 threads) needs about 9min to finish.

**Comment by lispc** [comment]
tx_circuit_1tx_2max_tx failed

**Comment by lispc** [comment]
@silathdiir oh each action run twice... in my above commit (push directly to scroll-stable). Can you help fix that?

**Comment by lispc** [comment]
wait me to fix this..

**Pull request merged**
