### PR TITLE
[bugs fix]: soundness bug in powers of challenges; witness gen bug

### PR DESCRIPTION
**Pull request by zhenfeizhang**
previous version the powers of challenges are not constrained in circuits. this pr fixes the bug; also does some clean up

### CODE REVIEW

**Comment by lispc** [comment]
commits before 
"more accurate rows per sig data" already squashed/merged. So we can rebase the last 4 commits as a new branch to solve the conflicts. (low priority)

**Comment by zhenfeizhang** [comment]
> commits before "more accurate rows per sig data" already squashed/merged. So we can rebase the last 4 commits as a new branch to solve the conflicts. (low priority)

sounds good. Let me get the parallization feature implemented first before rebasing and merge.

**Comment by lispc** [comment]
is this still relevant or can be closed?

**Comment by zhenfeizhang** [comment]
> is this still relevant or can be closed?

No... not relevant. Closed.

**Pull request closed without merging**
