### PR TITLE
fix: add logs and verify inner snark if failed to check pairing

### PR DESCRIPTION
**Pull request by silathdiir**
### Description

- add and update logs for paring check.
- try to verify inner snark if failed to check pairing.

### CODE REVIEW

**Comment by lispc** [comment]
this pr is useful. But we will keep using v0.9 for a long time. It is useful to also add these logs there?

**Comment by silathdiir** [comment]
> this pr is useful. But we will keep using v0.9 for a long time. It is useful to also add these logs there?

Yes, I see. Will rebase on `v0.9` branch, run `chunk_tests` (and try to test inner snark verification with fake failure code).

**Comment by silathdiir** [comment]
Test inner-snark could be verified (if pairing check was failed).

Screen Shot 2023-10-17 at 3 07 38 PM

**Comment by silathdiir** [comment]
Cannot reproduce for now.

**Pull request closed without merging**
