### PR TITLE
feat: implement mcopy opcode

### PR DESCRIPTION
**Pull request by DreamWuGit**
### Description

 implement mcopy opcode, also need to check if OOG memory copy needs change to support it.
- [ ] Buss mapping 
    - [x] add MCopy opcode
    - [x] generate copy steps/event 
    - [x] add tests 

- [ ] Circuit 
    - [x] Mcopy gadget
    - [x] copy circuit change  : no need
    - [x] add copy test for mcopy
- [ ] Testing
     - [x]  upgrade l1geth to support mcopy opcode
     - [ ] testing cases: 
         - [x] zero length copy
         - [x] real length copy: one slot + multi slots copy words
         - [x] oog cases for memory copy
         - [x] test tools testing fixed except last one（overlap read/write case）, will open another PR for it.

### Issue Link
issue #1203

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by DreamWuGit** [comment]
make ready for ci testing..

**Comment by lispc** [comment]
https://circuit-release.s3.us-west-2.amazonaws.com/testool/EIP5656.1714285755.430125f.html

**Comment by DreamWuGit** [comment]
Looking at rw lookup failure in https://circuit-release.s3.us-west-2.amazonaws.com/testool/EIP5656.1714305107.66e981c.html

**Comment by DreamWuGit** [comment]
looking at memory_word_size constraint failure in  https://circuit-release.s3.us-west-2.amazonaws.com/testool/EIP5656.1714394392.b8c2c83.html.  4 failures fixed, 12 remains

**Comment by lispc** [comment]
https://circuit-release.s3.us-west-2.amazonaws.com/testool/EIP5656.1714547413.7304bb3.html

**Comment by lispc** [comment]
final 3 errors 

https://circuit-release.s3.us-west-2.amazonaws.com/testool/EIP5656.1714572199.7304bb3.html

**Comment by DreamWuGit** [comment]
> final 3 errors
> 
> https://circuit-release.s3.us-west-2.amazonaws.com/testool/EIP5656.1714572199.7304bb3.html

will have a look tomorrow!

**Comment by DreamWuGit** [comment]
fixed `overflow when casting to u64` test tool error, left two now.

**Comment by DreamWuGit** [comment]
fixed second panic, remain last one

**Comment by lispc** [comment]
yes https://circuit-release.s3.us-west-2.amazonaws.com/testool/EIP5656.1714972091.dc111f3.html

**Pull request merged**
