### PR TITLE
grammar update README.md

### PR DESCRIPTION
**Pull request by s4t0shi-n4k4m0t0**
a few upper case and period updates to bullet points for consistency

### CODE REVIEW

**Comment by ultratwo** [comment]
Github farming meaningless PR. Please do not merge.

Please stop farming, it won't get you anywhere, and start doing more meaningful contributions.

**Comment by s4t0shi-n4k4m0t0** [comment]
Man, I just tried to learn how to create a pull request on github. Why this toxicity? The suggested changes do make sense in my eye.

**Comment by ultratwo** [comment]
Brand new account that started opening PRs with unmeaningful changes after the Starknet Airdrop.
This is airdrop farming, with a high chance of botting/automatisation, that make the work harder for real contributors, repos reviewers and injust to the user.

I would strongly recommand to close that type of PRs for the time being to contain the post-airdrop spam there's going to be due to some Twitter engagement bait post, to avoid proliferation, and doing the changes yourself if needed.

By rejecting those unmeaningful farming PRs, that newly found "github farm" strategy will be considerated ineffective and the spam will soon end, for the benefit of reviewers, devs, users and tech.

If you're doing that with no malicious intent, please consider doing more meaningful contributions.

Capture d’écran 2024-02-23 à 18 15 56

**Comment by s4t0shi-n4k4m0t0** [comment]
My account is 2 years or older. Your's is one week old.
I just checked about starknet airdrop. Seems like many people are butthurt by it and so are you?

**Comment by ultratwo** [comment]
You didn't make a single contribution during those 2 years. Your first one is now that github farming became a thing, even if it doesn't work.

I am not github farming, my profile is irrelevant.

Have a bit of shame and close that PR to save the reviewer's a bit of time. And start doing meaningful contribution.

**Comment by s4t0shi-n4k4m0t0** [comment]
Man, you must be fun at parties.

One has to start at some point. As I said this is me who just learned how to create a pull request on github. Give me some peace.

Go save yourself some time. I'll do so by not interacting with you anymore. Have a nice day.

**Pull request closed without merging**
