### PR TITLE
Fix grammar

### PR DESCRIPTION
**Pull request by kumakhov**
### Description

Fix multiple grammar mistakes and typos

### CODE REVIEW

**Comment by Fixue** [comment]
typo fix bot after starknet airdrop. "tx" does not mean "the".
please close to avoid the spread of the spamming wave.

**Comment by kumakhov** [comment]
huh, not really sure what you're talking about. 
you probably mixed up two different lines or something, i haven't changed "tx" to "the" anywhere, i absolutely know what does "tx" mean
i was reading scroll docs for like two weeks at this point and finally found some time to fix typos, so i did it

**Comment by ultratwo** [comment]
Account that started opening PRs with unmeaningful changes after the Starknet Airdrop.
This is airdrop farming, with a high chance of botting/automatisation, that make the work harder for real contributors and repos reviewers.

I would strongly recommand to close that type of PRs for the time being to contain the post-airdrop spam there's going to be due to some Twitter engagement bait post, to avoid proliferation, and doing the changes yourself if needed.

If you're doing that with no malicious intent, please consider doing more meaningful contributions.

**Comment by kumakhov** [comment]
well i'm not very active on github, i prefer stuff like codeberg or gitlab, and this is not my only github account, maybe that was the reason why you thought that i'm a bot, but i'm definitely not.

the reason for this PR was that i was reading docs myself and noticed some mistakes and typos, and i decided to fix them. if this PR is useless, maintainers will close it.

**Comment by kumakhov** [comment]
ok i've read about starknet airdrop, i kinda understand this reaction now, i don't want to encourage low quality prs from bots so i'll close this pr for now, maybe i'll resubmit it later :)

**Pull request closed without merging**
