### PR TITLE
Refactor: Move Eth and Evm types from bus-mapping to a new sub-crate eth-types

### PR DESCRIPTION
**Pull request by silathdiir**
Step-1 of PR https://github.com/scroll-tech/zkevm-circuits/pull/70

Related discussion in issue https://github.com/appliedzkp/zkevm-circuits/issues/272

### Summary

1. Move `eth_types.rs` of bus-mapping to `lib.rs` of  new sub-crate eth-types.
2. Move all files of `evm` of bus-mapping to `evm_types` of eth-types except `opcodes`.
3. Update code and test of bus-mapping and zkevm-circuits.

### CODE REVIEW

**Comment by lispc** [comment]
FYI there is a huge refactor here.  https://github.com/appliedzkp/zkevm-circuits/pull/287/files

**Review by HAOYUatHZ — CHANGES_REQUESTED** [review]
CI fails?

**Review by HAOYUatHZ — APPROVED** [review]
LGTM

**Comment by scroll-dev** [comment]
closed and moved to https://github.com/appliedzkp/zkevm-circuits/pull/290

**Pull request closed without merging**
