### PR TITLE
Pi aggregation circuit

### PR DESCRIPTION
**Pull request by zhenfeizhang**
### Description

[_PR description_]

### Issue Link

[_link issue here_]

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Contents

- [_item_]

### Rationale

[_design decisions and extended information_]

### How Has This Been Tested?

[_explanation_]

<hr>

## How to fill a PR description 

Please give a concise description of your PR.

The target readers could be future developers, reviewers, and auditors. By reading your description, they should easily understand the changes proposed in this pull request.

MUST: Reference the issue to resolve

### Single responsability

Is RECOMMENDED to create single responsibility commits, but not mandatory.

Anyway, you MUST enumerate the changes in a unitary way, e.g.

```
This PR contains:
- Cleanup of xxxx, yyyy
- Changed xxxx to yyyy in order to bla bla
- Added xxxx function to ...
- Refactored ....
```

### Design choices

RECOMMENDED to:
- What types of design choices did you face?
- What decisions you have made?
- Any valuable information that could help reviewers to think critically

### CODE REVIEW

**Comment by huwenqing0606** [comment]
is the chunk here (ChunkPublicData, each corresponds to a chunk with max_txn transactions) same as chunk for keccak hash inputs (17 * 8 * 8=1088 bits for each chunk)? I think each chunk has 300 Keccak rows but a hash may have 300 * num_chunk rows?

**Comment by zhenfeizhang** [comment]
> is the chunk here (ChunkPublicData, each corresponds to a chunk with max_txn transactions) same as chunk for keccak hash inputs (17 * 8 * 8=1088 bits for each chunk)? I think each chunk has 300 Keccak rows but a hash may have 300 * num_chunk rows?

Thanks for spotting this. It is fixed with f4082a2e973835dbd09717e062b24ba2f5af56ce, with your idea of using `is_final` cell

**Comment by huwenqing0606** [comment]
> Thanks for spotting this. It is fixed with [f4082a2](https://github.com/scroll-tech/zkevm-circuits/commit/f4082a2e973835dbd09717e062b24ba2f5af56ce), with your idea of using `is_final` cell

Great! I'll take a careful look. For the hardcoded 300, I think it may not be seriously hard to change to parameter-dependent. In general this 300 is replaced by NUM_ROWS_PER_ROUND * 25 (24+1 which is never changed in Keccak). Also, the hash output is always at row[last]. The only problem might be with the hash input, which currently we put at row[6]. When the num of lookup bits change, the `word split` and `transform` modules in keccak codebase may incur this 6 to be changed in a little complicated way.

**Comment by zhenfeizhang** [comment]
closed in favor of https://github.com/scroll-tech/scroll-zkevm/pull/143

**Pull request closed without merging**
