### PR TITLE
refactor: update the default sign_data

### PR DESCRIPTION
**Pull request by kunxian-xia**
### Description

This PR aims to refactor how the default sign data is created. Previously, the default sign data is generated through 
signing the msg(b"1") using 0x01 as the private key and 0x01 as the randomness `k`. This is different than the sign data of the padding tx that we use in the tx circuit and pi circuit. Therefore, this sign data is kind of out dated.

### Type of change

- [x] Refactor/Cleanup

### Contents

- The default sign data is updated as the sign data of default padding tx(a pre-eip155 tx signed by a dummy private key 0x01)
-

### CODE REVIEW

**Comment by lispc** [comment]
@kunxian-xia can you fix the CI here?

**Comment by lispc** [comment]
@kunxian-xia what is the status of this pr?

**Comment by kunxian-xia** [comment]
Sorry, I thought this has been merged! I will fix the CI errors asap.

**Comment by kunxian-xia** [comment]
@lispc ready for merge.

**Pull request merged**
