### PR TITLE
scroll mode for testool

### PR DESCRIPTION
**Pull request by lispc**
### Description

[_PR description_]

### Issue Link

[_link issue here_]

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Contents

- [_item_]

### Rationale

[_design decisions and extended information_]

### How Has This Been Tested?

[_explanation_]

<hr>

## How to fill a PR description 

Please give a concise description of your PR.

The target readers could be future developers, reviewers, and auditors. By reading your description, they should easily understand the changes proposed in this pull request.

MUST: Reference the issue to resolve

### Single responsability

Is RECOMMENDED to create single responsibility commits, but not mandatory.

Anyway, you MUST enumerate the changes in a unitary way, e.g.

```
This PR contains:
- Cleanup of xxxx, yyyy
- Changed xxxx to yyyy in order to bla bla
- Added xxxx function to ...
- Refactored ....
```

### Design choices

RECOMMENDED to:
- What types of design choices did you face?
- What decisions you have made?
- Any valuable information that could help reviewers to think critically

### CODE REVIEW

**Comment by lispc** [comment]
(low priority).  @noel2004   there seems to be something not thread safe in zktrie.  When i run this testool with scroll feature enabled using multi thread, the zktrie panics and has strange behavior.. Maybe there is something globally shared.. ?

**Comment by noel2004** [comment]
> (low priority). @noel2004 there seems to be something not thread safe in zktrie. When i run this testool with scroll feature enabled using multi thread, the zktrie panics and has strange behavior.. Maybe there is something globally shared.. ?

Concurrent access of `ZktrieState` or `ZkTrie` object is not thread safe. I would add `!Sync` trait on these two type so compiler could help us find where the issue is. Only if testtool do not include unsafe code.

**Comment by lispc** [comment]
@noel2004 after replay mpt updates, roots non consistent

**Comment by noel2004** [comment]
> @noel2004 after replay mpt updates, roots non consistent

Testtool set basefee to 10 by default in every cases. However our circuit never consider basefee. This cause divergence in the reward of coinbase

Change https://github.com/scroll-tech/zkevm-circuits/blob/2a6cc041ac0817fb1909b8590d8eb9387ff0d884/testool/src/statetest/yaml.rs#L208 to 0 can fix this issue but i do not know if such a change makes sense

**Comment by lispc** [comment]
\b run testool 1

**Comment by lispc** [comment]
another roots error

```
C="push0_d3(push0_upd_storage)_g0_v0"

#CHECK_RW_LOOKUP=true
FLAG=" --features=scroll"

RUST_BACKTRACE=1 RUST_LOG=trace cargo run --release $FLAG -- --circuits basic --inspect "${C}" 2>&1 | tee log
grep ERROR log
```

**Pull request merged**
